#!/bin/bash
# .ship-config.sh — project-level ship-harness config.
# Generated by ship-harness/install.sh on 2026-05-25T14:01:55Z.
# Review the auto-detected values below and adjust as needed.

# ---- Required ---------------------------------------------------------

export SHIP_REPO_SLUG="CherryStreet2020/CherryEnterpriseAssetManagement"
export GH="/Users/deandunagan/bin/gh"

# ---- Recommended ------------------------------------------------------

export SHIP_DEFAULT_BASE_BRANCH="main"

# Local build command. See .ship-config.example.sh in the skill bundle
# for examples per framework.
export SHIP_BUILD_CMD='$HOME/.dotnet/dotnet build Abs.FixedAssets.csproj --nologo -c Debug -v m --nodereuse:false --disable-build-servers'
export SHIP_BUILD_SUCCESS_RE='Build succeeded'

# Commit author identity. Optional — falls back to git's global config.
export SHIP_GIT_NAME="Dean Dunagan"
export SHIP_GIT_EMAIL="dunagan.dean@gmail.com"
