using Microsoft.EntityFrameworkCore.Migrations;

namespace Abs.FixedAssets.Migrations
{
    public partial class AddMachineSpecifications : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""MachineSpecifications"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""AssetId"" integer NOT NULL,
                    ""MachineTypeCode"" character varying(20) NULL,
                    ""MachineTypeLookupValueId"" integer NULL,
                    ""CncControlSystem"" character varying(100) NULL,
                    ""FiveAxisCapable"" boolean NOT NULL DEFAULT false,
                    ""SyncFeedTapping"" boolean NOT NULL DEFAULT false,
                    ""CoolantThroughSpindle"" boolean NOT NULL DEFAULT false,
                    ""AtcPocketCount"" integer NULL,
                    ""SpindleTaper"" character varying(20) NULL,
                    ""SpindleTaperLookupValueId"" integer NULL,
                    ""SpindleDiameterMm"" numeric(10,2) NULL,
                    ""MaxSpindleSpeedRpm"" integer NULL,
                    ""SpindleMotorHp"" numeric(10,2) NULL,
                    ""XAxisTravelMm"" numeric(12,2) NULL,
                    ""YAxisTravelMm"" numeric(12,2) NULL,
                    ""ZAxisTravelMm"" numeric(12,2) NULL,
                    ""WAxisTravelMm"" numeric(12,2) NULL,
                    ""MaxSwingDiameterMm"" numeric(12,2) NULL,
                    ""MaxBetweenColumnsMm"" numeric(12,2) NULL,
                    ""MaxHeightTableToRamMm"" numeric(12,2) NULL,
                    ""MaxCuttingDiameterMm"" numeric(12,2) NULL,
                    ""MaxCuttingLengthMm"" numeric(12,2) NULL,
                    ""TableSize"" character varying(50) NULL,
                    ""TableWeightCapacityKg"" numeric(12,2) NULL,
                    ""MachineWeightCapacityKg"" numeric(12,2) NULL,
                    ""EquippedHeads"" character varying(500) NULL,
                    ""ProbingSystem"" character varying(100) NULL,
                    ""DetailsSketchLink"" character varying(500) NULL,
                    ""Comments"" character varying(500) NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT now(),
                    ""ModifiedAt"" timestamp with time zone NULL,
                    ""TenantId"" integer NOT NULL DEFAULT 1,
                    ""CompanyId"" integer NULL,
                    CONSTRAINT ""PK_MachineSpecifications"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_MachineSpecifications_Assets_AssetId""
                        FOREIGN KEY (""AssetId"") REFERENCES ""Assets"" (""Id"") ON DELETE CASCADE
                );

                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_MachineSpecifications_AssetId""
                    ON ""MachineSpecifications"" (""AssetId"");

                CREATE INDEX IF NOT EXISTS ""IX_MachineSpecifications_TenantId""
                    ON ""MachineSpecifications"" (""TenantId"");
            ");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""MachineSpecifications"";");
        }
    }
}
