using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Abs.FixedAssets.Migrations
{
    public partial class AddLookupTables : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                ALTER TABLE ""MaintenanceEvents"" ADD COLUMN IF NOT EXISTS ""HoldReason"" VARCHAR(500);
                ALTER TABLE ""MaintenanceEvents"" ADD COLUMN IF NOT EXISTS ""StartedAt"" TIMESTAMP WITH TIME ZONE;
                ALTER TABLE ""MaintenanceEvents"" ADD COLUMN IF NOT EXISTS ""StartedBy"" VARCHAR(100);
            ");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""LookupTypes"" (
                    ""Id"" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""TenantId"" INTEGER REFERENCES ""Tenants""(""Id"") ON DELETE CASCADE,
                    ""CompanyId"" INTEGER REFERENCES ""Companies""(""Id"") ON DELETE CASCADE,
                    ""Key"" VARCHAR(100) NOT NULL,
                    ""Name"" VARCHAR(200) NOT NULL,
                    ""IsSystem"" BOOLEAN NOT NULL DEFAULT TRUE,
                    ""IsActive"" BOOLEAN NOT NULL DEFAULT TRUE,
                    ""CreatedAt"" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                    ""UpdatedAt"" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
                );
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_LookupTypes_TenantId_CompanyId_Key"" ON ""LookupTypes"" (""TenantId"", ""CompanyId"", ""Key"");
                CREATE INDEX IF NOT EXISTS ""IX_LookupTypes_CompanyId"" ON ""LookupTypes"" (""CompanyId"");
            ");

            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""LookupValues"" (
                    ""Id"" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""LookupTypeId"" INTEGER NOT NULL REFERENCES ""LookupTypes""(""Id"") ON DELETE CASCADE,
                    ""Code"" VARCHAR(50) NOT NULL,
                    ""Name"" VARCHAR(200) NOT NULL,
                    ""SortOrder"" INTEGER NOT NULL DEFAULT 0,
                    ""IsActive"" BOOLEAN NOT NULL DEFAULT TRUE,
                    ""Metadata"" JSONB,
                    ""CreatedAt"" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                    ""UpdatedAt"" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
                );
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_LookupValues_LookupTypeId_Code"" ON ""LookupValues"" (""LookupTypeId"", ""Code"");
                CREATE INDEX IF NOT EXISTS ""IX_LookupValues_LookupTypeId_IsActive_SortOrder"" ON ""LookupValues"" (""LookupTypeId"", ""IsActive"", ""SortOrder"");
            ");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "LookupValues");
            migrationBuilder.DropTable(name: "LookupTypes");
            migrationBuilder.DropColumn(name: "HoldReason", table: "MaintenanceEvents");
            migrationBuilder.DropColumn(name: "StartedAt", table: "MaintenanceEvents");
            migrationBuilder.DropColumn(name: "StartedBy", table: "MaintenanceEvents");
        }
    }
}
