// <auto-generated />
using Abs.FixedAssets.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Abs.FixedAssets.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260503000001_AddCompanyIdToCcaClassBalance")]
    partial class AddCompanyIdToCcaClassBalance
    {
        // BuildTargetModel is only consumed by `dotnet ef` tooling. Runtime
        // Database.Migrate() applies Up()/Down() based on the [Migration]
        // attribute and the snapshot in AppDbContextModelSnapshot.cs.
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
