using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Abs.FixedAssets.Migrations
{
    public partial class EnrichTechnicianModel : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                ALTER TABLE ""Technicians""
                  ADD COLUMN IF NOT EXISTS ""EmployeeId"" varchar(30),
                  ADD COLUMN IF NOT EXISTS ""PhotoPath"" varchar(500),
                  ADD COLUMN IF NOT EXISTS ""Title"" varchar(100),
                  ADD COLUMN IF NOT EXISTS ""CompanyId"" integer REFERENCES ""Companies""(""Id"") ON DELETE SET NULL,
                  ADD COLUMN IF NOT EXISTS ""SiteId"" integer REFERENCES ""Sites""(""Id"") ON DELETE SET NULL,
                  ADD COLUMN IF NOT EXISTS ""SupervisorTechnicianId"" integer REFERENCES ""Technicians""(""Id"") ON DELETE SET NULL,
                  ADD COLUMN IF NOT EXISTS ""PrimaryCraft"" varchar(50),
                  ADD COLUMN IF NOT EXISTS ""SecondaryCraft"" varchar(50),
                  ADD COLUMN IF NOT EXISTS ""ProficiencyLevel"" integer NOT NULL DEFAULT 0,
                  ADD COLUMN IF NOT EXISTS ""ShiftPattern"" varchar(30),
                  ADD COLUMN IF NOT EXISTS ""ShiftStart"" time,
                  ADD COLUMN IF NOT EXISTS ""ShiftEnd"" time,
                  ADD COLUMN IF NOT EXISTS ""OvertimeRate"" numeric(10,2),
                  ADD COLUMN IF NOT EXISTS ""DoubleTimeRate"" numeric(10,2),
                  ADD COLUMN IF NOT EXISTS ""HireDate"" timestamptz,
                  ADD COLUMN IF NOT EXISTS ""EmergencyContactName"" varchar(100),
                  ADD COLUMN IF NOT EXISTS ""EmergencyContactPhone"" varchar(30),
                  ADD COLUMN IF NOT EXISTS ""TenantId"" integer;

                CREATE INDEX IF NOT EXISTS ""IX_Technicians_CompanyId"" ON ""Technicians"" (""CompanyId"");
                CREATE INDEX IF NOT EXISTS ""IX_Technicians_SiteId"" ON ""Technicians"" (""SiteId"");
                CREATE INDEX IF NOT EXISTS ""IX_Technicians_EmployeeId"" ON ""Technicians"" (""EmployeeId"");

                CREATE TABLE IF NOT EXISTS ""TechnicianCertifications"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""TechnicianId"" integer NOT NULL REFERENCES ""Technicians""(""Id"") ON DELETE CASCADE,
                    ""Name"" varchar(100) NOT NULL,
                    ""CertificateNumber"" varchar(50),
                    ""IssuingAuthority"" varchar(100),
                    ""IssueDate"" timestamptz,
                    ""ExpirationDate"" timestamptz,
                    ""IsRequired"" boolean NOT NULL DEFAULT false,
                    ""Notes"" varchar(500),
                    ""TenantId"" integer
                );

                CREATE TABLE IF NOT EXISTS ""TechnicianSkills"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""TechnicianId"" integer NOT NULL REFERENCES ""Technicians""(""Id"") ON DELETE CASCADE,
                    ""SkillName"" varchar(100) NOT NULL,
                    ""Category"" varchar(50),
                    ""ProficiencyLevel"" integer NOT NULL DEFAULT 0,
                    ""IsCertified"" boolean NOT NULL DEFAULT false,
                    ""LastAssessedDate"" timestamptz,
                    ""Notes"" varchar(500),
                    ""TenantId"" integer
                );

                CREATE INDEX IF NOT EXISTS ""IX_TechnicianCertifications_TechnicianId"" ON ""TechnicianCertifications"" (""TechnicianId"");
                CREATE INDEX IF NOT EXISTS ""IX_TechnicianSkills_TechnicianId"" ON ""TechnicianSkills"" (""TechnicianId"");
            ");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(name: "TechnicianSkills");
            migrationBuilder.DropTable(name: "TechnicianCertifications");

            migrationBuilder.DropIndex(name: "IX_Technicians_CompanyId", table: "Technicians");
            migrationBuilder.DropIndex(name: "IX_Technicians_SiteId", table: "Technicians");
            migrationBuilder.DropIndex(name: "IX_Technicians_EmployeeId", table: "Technicians");

            migrationBuilder.DropColumn(name: "EmployeeId", table: "Technicians");
            migrationBuilder.DropColumn(name: "PhotoPath", table: "Technicians");
            migrationBuilder.DropColumn(name: "Title", table: "Technicians");
            migrationBuilder.DropColumn(name: "CompanyId", table: "Technicians");
            migrationBuilder.DropColumn(name: "SiteId", table: "Technicians");
            migrationBuilder.DropColumn(name: "SupervisorTechnicianId", table: "Technicians");
            migrationBuilder.DropColumn(name: "PrimaryCraft", table: "Technicians");
            migrationBuilder.DropColumn(name: "SecondaryCraft", table: "Technicians");
            migrationBuilder.DropColumn(name: "ProficiencyLevel", table: "Technicians");
            migrationBuilder.DropColumn(name: "ShiftPattern", table: "Technicians");
            migrationBuilder.DropColumn(name: "ShiftStart", table: "Technicians");
            migrationBuilder.DropColumn(name: "ShiftEnd", table: "Technicians");
            migrationBuilder.DropColumn(name: "OvertimeRate", table: "Technicians");
            migrationBuilder.DropColumn(name: "DoubleTimeRate", table: "Technicians");
            migrationBuilder.DropColumn(name: "HireDate", table: "Technicians");
            migrationBuilder.DropColumn(name: "EmergencyContactName", table: "Technicians");
            migrationBuilder.DropColumn(name: "EmergencyContactPhone", table: "Technicians");
            migrationBuilder.DropColumn(name: "TenantId", table: "Technicians");
        }
    }
}
